name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

permissions:
  contents: write

env:
  TAG: ${{ github.event.inputs.tag || github.ref_name }}

jobs:
  build-app:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: choco install ffmpeg --no-progress

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Set up python env
        run: uv sync --locked --all-extras --dev

      - name: Build Windows app
        env:
          PYTHONIOENCODING: utf-8
        run: uv run scripts/build.py --debug

      - name: Get changelog
        id: get-changelog
        shell: bash
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Delete existing asset
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ASSET_NAME="MDCx-${{ env.TAG }}-windows-x86_64.exe"
          gh release delete-asset "${{ env.TAG }}" "$ASSET_NAME" -y 2>/dev/null || true

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: MDCx-${{ env.TAG }}-windows-x86_64.exe
          file: dist/MDCx.exe
          prerelease: ${{ !startsWith(env.TAG, '220') }}
          body: ${{ steps.get-changelog.outputs.CHANGELOG }}
          tag: ${{ env.TAG }}
